### PR TITLE
Fixes and run R-CMD-CHECK on GitHub CI

### PR DESCRIPTION
**Pull request by asiripanich**
Thanks for making `onnx` models accessible to R users!

I found a few problems when I tried to run [this example](https://onnx.ai/onnx-r/articles/onnx_model_zoo.html). This PR should address some of them.

You may also want to revise your unit tests and code to make sure that they are up-to-date with the latest development on `onnx`. For example, it seems that `make_node("Relu", list("X"), list("Y"))` no longer returns a `onnx.onnx_ml_pb2.NodeProto` object, that is why the test below fails.

https://github.com/onnx/onnx-r/blob/b5037a21d882fe7778e993cebfc7ca9ec09d09f6/tests/testthat/test_everything.R#L8-L9

### CODE REVIEW

**Comment by asiripanich** [comment]
Here is a test result:

```r
> devtools::test()
ℹ Loading onnx
ℹ Testing onnx
✓ |  OK F W S | Context
x |   0 2     | everything                                                        
──────────────────────────────────────────────────────────────────────────────────
Failure (setup.R:17:5): onnx works
`force(expr)` threw an error.
Message: inherits(node_def, "onnx_pb2.NodeProto") is not TRUE

`actual`:   FALSE
`expected`: TRUE 
Class:   expectation_failure/expectation/error/condition
Backtrace:
 1. testthat::expect_error(force(expr), NA) setup.R:17:4
 7. testthat::expect_true(inherits(node_def, "onnx_pb2.NodeProto")) test_everything.R:3:2

Failure (setup.R:17:5): onnx_tf works
`force(expr)` threw an error.
Message: could not find function "import"
Class:   simpleError/error/condition
Backtrace:
 1. testthat::expect_error(force(expr), NA) setup.R:17:4
 6. base::force(expr)
──────────────────────────────────────────────────────────────────────────────────

══ Results ═══════════════════════════════════════════════════════════════════════
[ FAIL 2 | WARN 0 | SKIP 0 | PASS 0 ]
```

**Review by terrytangyuan — COMMENTED** [review]
Thanks! Would you like to help fix the tests as well?

**Comment by asiripanich** [comment]
Would love to! but unfortunately I won't be able to contribute more on this until next month. I will check again next month. :)

**Review by terrytangyuan — APPROVED** [review]
Sounds good. Let's merge this for now. Feel free to submit additional PRs.

**Pull request merged**
